version: '3'

services:
  app:
    container_name: dev_deneral
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./src
        target: /src
    tty: true
